# Generated by Django 6.0.4 on 2026-04-22 15:22

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(verbose_name='Ism')),
                ('last_name', models.CharField(verbose_name='Familiya')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Telefon raqam')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil rasmi')),
                ('address', models.CharField(max_length=255, verbose_name='Yashash manzili')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodimlik statusi')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superadminlik statusi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil aktivligi holati')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maxsulot narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsulot rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Maxsulot ta'rifi")),
                ('in_stock', models.IntegerField(default=1, verbose_name='Ombordagi soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.category', verbose_name='Maxsulot kategoriyasi')),
            ],
        ),
    ]
