# Generated by Django 6.0.4 on 2026-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_cart_options_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
