# Generated by Django 6.0.4 on 2026-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_transaction_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
