# Generated by Django 5.2.14 on 2026-05-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_transaction_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created', 'amount'], 'verbose_name': 'Oldi-berdi', 'verbose_name_plural': 'Oldi-berdilar'},
        ),
    ]
